const fs=require("fs"),path=require("path"),crypto=require("crypto");
const FOLDER_ID=process.env.BC_DRIVE_FOLDER_ID||"1ah__K2w_vqsIX0o92OaEHv5mVasq-JrV";
const TEMPLATE_URL="https://drive.google.com/uc?export=download&id=1Rm7MsfjYH_ryS9Tpc3-AwSbgVv5Y-kB7";
const CACHE=path.join(__dirname,"data","bc_report","bc_template.html");
const LOCAL_DIR=process.env.BC_DATA_DIR||"/tmp/bc";
function b64url(x){return Buffer.from(x).toString("base64").replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
function hasDriveCredentials(){return !!(process.env.GOOGLE_SERVICE_ACCOUNT_JSON||process.env.GOOGLE_CREDENTIALS_JSON||process.env.GOOGLE_ACCESS_TOKEN)}
async function accessToken(){if(process.env.GOOGLE_ACCESS_TOKEN)return process.env.GOOGLE_ACCESS_TOKEN;const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON||process.env.GOOGLE_CREDENTIALS_JSON;if(!raw)throw new Error("Thiếu Google credentials");const c=typeof raw==="string"?JSON.parse(raw):raw,now=Math.floor(Date.now()/1000),head=b64url(JSON.stringify({alg:"RS256",typ:"JWT"})),body=b64url(JSON.stringify({iss:c.client_email,scope:"https://www.googleapis.com/auth/drive",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600})),sign=crypto.createSign("RSA-SHA256");sign.update(`${head}.${body}`);sign.end();const assertion=`${head}.${body}.${sign.sign(c.private_key,"base64url")}`,r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${encodeURIComponent(assertion)}`});if(!r.ok)throw new Error(`Google OAuth ${r.status}: ${await r.text()}`);return(await r.json()).access_token}
async function drive(pathname,opts={}){const token=await accessToken(),r=await fetch(`https://www.googleapis.com/drive/v3${pathname}`,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Drive ${r.status}: ${await r.text()}`);return r}
async function downloadTemplate(){fs.mkdirSync(path.dirname(CACHE),{recursive:true});try{const r=await fetch(TEMPLATE_URL);if(!r.ok)throw new Error(`template ${r.status}`);const text=await r.text();if(!text.includes('const DATA = "__BC_DATA__";'))throw new Error("Khuôn mẫu Drive thiếu placeholder __BC_DATA__");fs.writeFileSync(CACHE,text,"utf8");return text}catch(e){if(fs.existsSync(CACHE)){const text=fs.readFileSync(CACHE,"utf8");if(text.includes('const DATA = "__BC_DATA__";')){console.warn("⚠️ DRIVE TEMPLATE → dùng bản cache gần nhất:",e.message);return text}}throw new Error(`Không tải được khuôn mẫu Drive và chưa có bản cache: ${e.message}`)}}
function applyTemplate(template,data){const marker='const DATA = "__BC_DATA__";';if(!template.includes(marker))throw new Error("Khuôn mẫu không đúng placeholder");return template.replace(marker,`const DATA = ${JSON.stringify(data)};`)}
function localPath(name){return path.join(LOCAL_DIR,path.basename(name))}
function putLocalJson(name,data){fs.mkdirSync(LOCAL_DIR,{recursive:true});const file=localPath(name),text=JSON.stringify(data,null,2);fs.writeFileSync(file,text,"utf8");const size=fs.statSync(file).size;if(size<=0){console.error(`❌ LOCAL BC WRITE EMPTY → ${file}`);throw new Error(`Local BC ghi file rỗng: ${name}`)}console.log(`💾 LOCAL BC JSON → ${file} | ${size} bytes`);return file}
function readLocalJson(name){const file=localPath(name);if(!fs.existsSync(file)||fs.statSync(file).size<=0)return null;try{return JSON.parse(fs.readFileSync(file,"utf8"))}catch(e){console.warn(`⚠️ LOCAL BC READ ERROR → ${file}:`,e.message);return null}}
function latestLocalJson(){if(!fs.existsSync(LOCAL_DIR))return null;const files=fs.readdirSync(LOCAL_DIR).filter(n=>/^bc-\d{4}-\d{2}-\d{2}\.json$/.test(n)).map(n=>{const file=path.join(LOCAL_DIR,n);let st;try{st=fs.statSync(file)}catch{return null}return st.size>0?{name:n,file,mtime:st.mtimeMs}:null}).filter(Boolean).sort((a,b)=>b.mtime-a.mtime);if(!files.length)return null;try{return{name:files[0].name,data:JSON.parse(fs.readFileSync(files[0].file,"utf8"))}}catch(e){console.warn(`⚠️ LOCAL BC LATEST ERROR → ${files[0].file}:`,e.message);return null}}
async function findFile(name){const q=encodeURIComponent(`'${FOLDER_ID}' in parents and name='${name.replace(/'/g,"\\'")}' and trashed=false`),r=await drive(`/files?q=${q}&fields=files(id,name,size,modifiedTime,mimeType)&pageSize=10`),j=await r.json();return j.files&&j.files[0]||null}
async function putJson(name,data){if(!hasDriveCredentials()){console.log(`ℹ️ DRIVE JSON SKIP → chưa có Google credentials | ${name}`);return null}const existing=await findFile(name),metadata={name,parents:existing?undefined:[FOLDER_ID],mimeType:"application/json"},boundary="bc_boundary_"+Date.now(),body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n`),Buffer.from(JSON.stringify(data,null,2)),Buffer.from(`\r\n--${boundary}--`)]),method=existing?"PATCH":"POST",url=existing?`/files/${existing.id}?uploadType=multipart`:"/files?uploadType=multipart",r=await drive(url,{method,headers:{"Content-Type":`multipart/related; boundary=${boundary}`},body}),saved=await r.json();if(!saved.id)throw new Error("Drive không trả file id");const meta=await(await drive(`/files/${saved.id}?fields=id,name,size,modifiedTime`)).json(),size=Number(meta.size||0);if(size<=0){console.error(`❌ DRIVE WRITE EMPTY → ${name}`);throw new Error(`Drive ghi file rỗng: ${name}`)}console.log(`💾 DRIVE JSON → ${name} | ${size} bytes`);return saved}
async function readJson(name){if(hasDriveCredentials()){const f=await findFile(name);if(!f)return null;const r=await drive(`/files/${f.id}?alt=media`);return JSON.parse(await r.text())}return null}
async function latestJson(){if(!hasDriveCredentials())return null;const q=encodeURIComponent(`'${FOLDER_ID}' in parents and trashed=false and name contains '.json'`),r=await drive(`/files?q=${q}&orderBy=modifiedTime desc&fields=files(id,name,size,modifiedTime)&pageSize=20`),j=await r.json(),f=(j.files||[]).find(x=>Number(x.size||0)>0);if(!f)return null;return{name:f.name,data:JSON.parse(await(await drive(`/files/${f.id}?alt=media`)).text())}}
async function listJson(prefix="",limit=20){if(!hasDriveCredentials())return [];const safe=String(prefix).replace(/'/g,"\\'");const q=encodeURIComponent("'"+FOLDER_ID+"' in parents and trashed=false and name contains '"+safe+"'");const r=await drive("/files?q="+q+"&orderBy=modifiedTime desc&fields=files(id,name,size,modifiedTime)&pageSize="+Math.min(100,Math.max(1,limit)));const j=await r.json(),files=(j.files||[]).filter(f=>Number(f.size||0)>0&&String(f.name||"").startsWith(prefix)).slice(0,limit),out=[];for(const f of files){try{const rr=await drive("/files/"+f.id+"?alt=media");out.push({name:f.name,data:JSON.parse(await rr.text())})}catch(e){console.warn("⚠️ DRIVE LIST JSON READ",f.name,e.message)}}return out}
module.exports={downloadTemplate,applyTemplate,putJson,putLocalJson,readLocalJson,latestLocalJson,readJson,latestJson,listJson,hasDriveCredentials,TEMPLATE_URL,FOLDER_ID,LOCAL_DIR};