const fs=require("fs"),path=require("path"),XLSX=require("xlsx"),report=require("./bc_report");
const STORE=path.join(__dirname,"data","bc_report","latest_store.xlsx"),GROUPS=["FMCG","FRESH","ĐÔNG MÁT"],KEYS={"FMCG":"fmcg","FRESH":"fresh","ĐÔNG MÁT":"mat"};
function money(v){return(Number(v)||0)/1e6}
function dateIso(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
function dateLabel(d){const x=new Date(d);return `${String(x.getDate()).padStart(2,"0")}/${String(x.getMonth()+1).padStart(2,"0")}/${x.getFullYear()}`}
function dateShort(d){const x=new Date(d);return `${String(x.getDate()).padStart(2,"0")}/${String(x.getMonth()+1).padStart(2,"0")}`}
function groupMap(items){const m={fmcg:[],fresh:[],mat:[]};for(const x of items||[])m[KEYS[x.group]||"fmcg"].push(x);return m}
function makeNhom(items,total){return GROUPS.map(name=>{const arr=(items||[]).filter(x=>x.group===name),sum=arr.reduce((a,x)=>a+Number(x.value||0),0);return{key:KEYS[name],ten:name,tong:money(sum),pct:total?sum/total*100:0,soNganh:arr.length}})}
function makeDetail(items){const m=groupMap(items),out={};for(const k of ["fmcg","fresh","mat"]){const total=m[k].reduce((a,x)=>a+Number(x.value||0),0);out[k]=m[k].map(x=>[String(x.name),money(x.value),total?Number(x.value||0)/total*100:0])}return out}
function makeIndustryCompare(s18,s17,moc){const out={moc,fmcg:[],fresh:[],mat:[]},a=groupMap(s18),b=groupMap(s17);for(const k of ["fmcg","fresh","mat"]){const names=new Set([...a[k].map(x=>x.name),...b[k].map(x=>x.name)]);out[k]=[...names].sort().map(name=>{const now=Number((a[k].find(x=>x.name===name)||{}).value||0),prev=Number((b[k].find(x=>x.name===name)||{}).value||0);return[String(name),money(now),money(prev),prev?(now/prev-1)*100:0]})}return out}
function readStoreTrend(latest){if(!fs.existsSync(STORE))return[];const wb=XLSX.readFile(STORE,{cellDates:true}),rows=[];for(const sn of wb.SheetNames)rows.push(...XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:null,raw:true}));const first=rows.find(x=>x&&Object.keys(x).length)||{};const key=(names,re)=>{const ks=Object.keys(first);for(const n of names){const hit=ks.find(x=>String(x).trim().toLowerCase()===n.toLowerCase());if(hit)return hit}return ks.find(x=>re.test(String(x).toLowerCase()))};const kd=key(["Ngày"],/^ngày$/),ki=key(["Mã siêu thị"],/ma sieu thi/),ko=key(["Doanh thu offline"],/doanh thu offline/),kn=key(["Doanh thu Online"],/doanh thu online/);const dt=v=>{if(v instanceof Date&&!isNaN(v))return v;if(typeof v==="number"){const x=XLSX.SSF.parse_date_code(v);return x?new Date(x.y,x.m-1,x.d):null}const s=String(v??"").trim(),m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const d=new Date(s);return isNaN(d)?null:d};const num=v=>typeof v==="number"?(Number.isFinite(v)?v:0):(Number(String(v??"").replace(/[^\d.-]/g,""))||0);const map=new Map();for(const r of rows){const d=dt(r[kd]),id=String(r[ki]??"").trim();if(!d||id!=="28717"||d>latest)continue;const k=dateIso(d),cur=map.get(k)||{ngay:k,tong:0,offline:0,online:0};cur.offline+=num(r[ko]);cur.online+=num(r[kn]);cur.tong+=num(r[ko])+num(r[kn]);map.set(k,cur)}return[...map.values()].sort((a,b)=>a.ngay.localeCompare(b.ngay)).map(x=>({ngay:x.ngay,tong:money(x.tong),offline:money(x.offline),online:money(x.online)}))}
function buildData(){const r=report.data(),d=new Date(r.latest),prev=new Date(d);prev.setDate(prev.getDate()-1);const todayTotal=Number(r.total18||0),prevTotal=Number(r.total17||0),mtdTotal=Number(r.totalm||0),todayItems=r.s18.FMCG.concat(r.s18.FRESH,r.s18["ĐÔNG MÁT"]),prevItems=r.s17.FMCG.concat(r.s17.FRESH,r.s17["ĐÔNG MÁT"]),mtdItems=r.sm.FMCG.concat(r.sm.FRESH,r.sm["ĐÔNG MÁT"]);const day={nhan:dateLabel(d),nhanNgan:dateShort(d),tong:money(todayTotal),offline:{v:money(r.st.today.off),p:todayTotal?r.st.today.off/todayTotal*100:0},online:{v:money(r.st.today.on),p:todayTotal?r.st.today.on/todayTotal*100:0},bill:{so:Number(r.st.today.bill||0),tb:r.st.today.bill?money(todayTotal/r.st.today.bill):0},soSanh:{nhan:money(todayTotal),pct:Number(r.growth||0),truoc:money(prevTotal),sau:money(todayTotal)},nhom:makeNhom(todayItems,todayTotal),chiTiet:makeDetail(todayItems),soSanhNganh:makeIndustryCompare(todayItems,prevItems,dateLabel(prev))};const days=Math.max(1,d.getDate()),projTotal=mtdTotal/days*31,projOff=Number(r.st.mtd.off||0)/days*31,projOn=Number(r.st.mtd.on||0)/days*31;const luyKe={nhan:`01 → ${dateLabel(d)}`,nhanNgan:`01 → ${dateShort(d)}`,soNgay:days,tong:money(mtdTotal),offline:{v:money(r.st.mtd.off),p:mtdTotal?r.st.mtd.off/mtdTotal*100:0},online:{v:money(r.st.mtd.on),p:mtdTotal?r.st.mtd.on/mtdTotal*100:0},bill:{so:Number(r.st.mtd.bill||0),tb:r.st.mtd.bill?money(mtdTotal/r.st.mtd.bill):0},duKien:{tong:money(projTotal),offline:{v:money(projOff),p:projTotal?projOff/projTotal*100:0},online:{v:money(projOn),p:projTotal?projOn/projTotal*100:0}},theoNgay:readStoreTrend(d),nhom:makeNhom(mtdItems,mtdTotal),chiTiet:makeDetail(mtdItems)};return{sieuThi:"MỸ QUỚI",ma:"28717",ngay:day,luyKe}}
module.exports={buildData};