const fs=require('fs'),path=require('path');
const DIR=process.env.BC_DATA_DIR||'/tmp/bc',FILE=path.join(DIR,'lich-ca.json');fs.mkdirSync(DIR,{recursive:true});
const CA={1:{gio:'6h-8h',dai:2,buoi:'SÁNG'},2:{gio:'8h-12h',dai:4,buoi:'SÁNG'},3:{gio:'12h-14h',dai:2,buoi:'SÁNG'},4:{gio:'14h-16h',dai:2,buoi:'CHIỀU'},5:{gio:'16h-18h',dai:2,buoi:'CHIỀU'},6:{gio:'18h-21h',dai:3,buoi:'CHIỀU'}};
const hai=n=>String(n).padStart(2,'0');const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function docLichCa(rows,nam){const year=nam||new Date().getFullYear(),s=o=>String(o??'').trim(),dayRe=/\(\s*\d{1,2}\s*\/\s*\d{1,2}\s*\)/,caRe=/^ca\s*[1-6]$/i;let dr=-1,dc=-1,max=0;for(let r=0;r<Math.min(rows.length,20);r++){const n=(rows[r]||[]).filter(x=>dayRe.test(s(x))).length;if(n>max){max=n;dr=r}}if(dr<0)throw Error('Không tìm thấy dòng ngày lịch ca');for(let r=dr;r<=dr+2;r++){if((rows[r]||[]).filter(x=>caRe.test(s(x))).length>=3){dc=r;break}}if(dc<0)throw Error('Không tìm thấy dòng Ca 1..Ca 6');const hd=rows[dr]||[],hc=rows[dc]||[];let nameCol=hc.findIndex(x=>norm(x).replace(/\s+/g,'')==='ho ten');if(nameCol<0)nameCol=hc.findIndex(x=>/h[ọo]\s*t[êe]n/i.test(s(x)));if(nameCol<0)nameCol=1;const marks=[];for(let c=0;c<hd.length;c++){const m=s(hd[c]).match(/\(\s*(\d{1,2})\s*\/\s*(\d{1,2})\s*\)/);if(m)marks.push({c,d:+m[1],m:+m[2]})}if(!marks.length)throw Error('Không đọc được ngày');const out={};marks.forEach((x,i)=>{const end=i+1<marks.length?marks[i+1].c:Math.max(hd.length,hc.length);const cols={};for(let c=x.c;c<end;c++){const m=s(hc[c]).match(/^ca\s*([1-6])$/i);if(m)cols[+m[1]]=c}let y=year;if(i&&x.m<marks[i-1].m)y++;const key=`${y}-${hai(x.m)}-${hai(x.d)}`;for(let r=dc+1;r<rows.length;r++){const row=rows[r]||[],name=s(row[nameCol]);if(!name||/h[ọo]\s*t[êe]n/i.test(name))continue;const shifts={};for(let ca=1;ca<=6;ca++){const c=cols[ca];if(c===undefined)continue;const v=row[c],num=typeof v==='number'?v:parseFloat(s(v).replace(',','.'));if(Number.isFinite(num)&&num>0)shifts[ca]=num}if(Object.keys(shifts).length)(out[key]||(out[key]={}))[name]=shifts}});if(!Object.keys(out).length)throw Error('Không có dữ liệu nhân viên');return out}
function dongBang(x){if(x&&typeof x==='object'){Object.freeze(x);Object.values(x).forEach(dongBang)}return x}
function docLich(){try{const x=JSON.parse(fs.readFileSync(FILE,'utf8'));return x&&typeof x==='object'?dongBang(x):{}}catch{return{}}}
function luuLich(n){if(!n||typeof n!=='object'||!Object.keys(n).length)throw Error('Lịch mới rỗng');const old=docLich(),merged={...old,...n};for(const [ngay,ds] of Object.entries(n)){if(!ds||typeof ds!=='object'||!Object.keys(ds).length)throw Error(`Dữ liệu lịch ngày ${ngay} rỗng`)}fs.mkdirSync(DIR,{recursive:true});const tmp=FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(merged,null,2));fs.renameSync(tmp,FILE);const ds=Object.keys(n).sort();return{soNgayMoi:ds.length,tuNgay:ds[0],denNgay:ds[ds.length-1],soNgayTong:Object.keys(merged).length}}
function theCaNgay(lich,ngay){const d=ngay instanceof Date?ngay:new Date(ngay),k=`${d.getFullYear()}-${hai(d.getMonth()+1)}-${hai(d.getDate())}`,day=lich?.[k];if(!day)return{type:'flex',altText:`Chưa có lịch ${k}`,contents:{type:'bubble',body:{type:'box',layout:'vertical',contents:[{type:'text',text:'CA LÀM VIỆC',weight:'bold',size:'lg'},{type:'text',text:k,weight:'bold',size:'xl'},{type:'text',text:'Chưa có lịch cho ngày này.',size:'sm',color:'#7b8798',margin:'md'}]}}};const groups=[['SÁNG',[1,2,3],'#1d4ed8','#eff5ff'],['CHIỀU',[4,5,6],'#0f9d58','#f0fdf4']];const lines=[];for(const [buoi,cas,mau,nen] of groups){const nguoi=Object.entries(day).map(([name,shifts])=>({name,ca:cas.filter(c=>shifts[c])})).filter(x=>x.ca.length);const rows=nguoi.map(x=>({type:'text',text:`+ ${x.name} - CA ${x.ca.join('')}`,size:'sm',wrap:true,color:'#334155',margin:'sm'}));lines.push({type:'box',layout:'vertical',backgroundColor:nen,cornerRadius:'10px',paddingAll:'12px',margin:'md',contents:[{type:'text',text:buoi,weight:'bold',size:'md',color:mau},...(rows.length?rows:[{type:'text',text:'+ Chưa có nhân viên',size:'sm',color:'#94a3b8',margin:'sm'}])]})}return{type:'flex',altText:`Ca làm việc ${k}`,contents:{type:'bubble',size:'kilo',body:{type:'box',layout:'vertical',paddingAll:'16px',contents:[{type:'text',text:'CA LÀM VIỆC',size:'xs',weight:'bold',color:'#7b8798'},{type:'text',text:k,size:'xl',weight:'bold',color:'#0b2452',margin:'xs'},...lines]}}}}
module.exports={docLichCa,luuLich,docLich,theCaNgay,CA};