const express=require('express');const crypto=require('crypto');const fs=require('fs');const path=require('path');const XLSX=require('xlsx');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.LINE_CHANNEL_SECRET,TOKEN=process.env.LINE_CHANNEL_ACCESS_TOKEN;
const DATA=path.join(__dirname,'data'),UPLOADS=path.join(DATA,'uploads'),STATE=path.join(DATA,'health_state.json'),DT=path.join(DATA,'dt_state.json'),HEALTH=path.join(__dirname,'health.html');fs.mkdirSync(UPLOADS,{recursive:true});
const num=v=>typeof v==='number'?v:(Number(String(v??'').replace(/[^\d.-]/g,''))||0);
function date(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==='number'){const x=XLSX.SSF.parse_date_code(v);return x?new Date(x.y,x.m-1,x.d):null}const s=String(v||'').trim(),m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const d=new Date(s);return isNaN(d)?null:d}
function key(r,names){const ks=Object.keys(r||{});for(const n of names){const x=ks.find(z=>String(z).trim().toLowerCase()===n.toLowerCase());if(x)return x}return null}
function read(file){const wb=XLSX.readFile(file,{cellDates:true});let a=[];for(const sn of wb.SheetNames)a=a.concat(XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:null,raw:true}));return a}
function uploads(){return fs.readdirSync(UPLOADS).filter(f=>/\.(xlsx|xls|csv)$/i.test(f)).map(f=>({name:f,path:path.join(UPLOADS,f),time:fs.statSync(path.join(UPLOADS,f)).mtimeMs})).sort((a,b)=>a.time-b.time)}
function load(){try{return JSON.parse(fs.readFileSync(STATE,'utf8'))}catch{return {locked:false,monthly:[],catMonth:{5:[],6:[],7:[],8:[]},catComp:[],lastProcessedAt:0}}}function save(s){fs.writeFileSync(STATE,JSON.stringify(s))}
function parse(rows){const rev={5:{offline:0,online:0,bills:0,dt:0},6:{offline:0,online:0,bills:0,dt:0},7:{offline:0,online:0,bills:0,dt:0},8:{offline:0,online:0,bills:0,dt:0}},cats={5:{},6:{},7:{},8:{}};for(const r of rows){const d=date(r[key(r,['Ngày','Date','Ngày bán','Ngày xuất'])]);if(!d)continue;const m=d.getMonth()+1;if(m<5||m>8)continue;const off=key(r,['Doanh thu offline','Doanh thu Offline']),on=key(r,['Doanh thu Online','Doanh thu online']),bill=key(r,['Tổng số bill','Tổng bill','Bill']),cat=key(r,['Ngành hàng BHX','Ngành hàng']),sales=key(r,['Doanh thu']);if(off||on){rev[m].offline+=num(r[off]);rev[m].online+=num(r[on]);rev[m].bills+=num(r[bill]);rev[m].dt+=num(r[off])+num(r[on])}if(cat&&sales){const name=String(r[cat]||'Chưa phân loại').trim();cats[m][name]=(cats[m][name]||0)+num(r[sales])}}return {rev,cats}}
function inject(s){let h=fs.readFileSync(HEALTH,'utf8'),a=h.indexOf('const monthly='),b=h.indexOf('let selected=8;',a);if(a<0||b<0)throw Error('health.html sai mẫu');const vars=`const monthly=${JSON.stringify(s.monthly||[])};const daily=[];const sameOverall=${JSON.stringify(s.sameOverall||{})};const catMonth=${JSON.stringify(s.catMonth||{})};const catComp=${JSON.stringify(s.catComp||[])};const sameCat=${JSON.stringify(s.sameCat||{})};const stores=[];`;fs.writeFileSync(HEALTH,h.slice(0,a)+vars+h.slice(b))}
function ingest(){const old=load(),files=uploads();if(!files.length)throw Error('Chưa có file SỨC KHỎE');let rows=[];for(const f of files){try{rows.push(...read(f.path))}catch(e){console.error(e)}}if(!rows.length)throw Error('File không có dữ liệu đọc được');const p=parse(rows);const baselineBad=old.locked&&([5,6,7].some(m=>!old.catMonth?.[m]?.length)||!old.catComp?.length);let s=old;if(!old.locked||baselineBad){if([5,6,7].some(m=>p.rev[m].dt===0&&Object.keys(p.cats[m]).length===0))throw Error('Cần đủ dữ liệu T5, T6, T7 trước khi khóa.');s={...old,locked:true,lockedMonths:[5,6,7],monthly:[5,6,7].map(m=>({Tháng:m,...p.rev[m]})),catMonth:{5:[],6:[],7:[],8:[]},catComp:[]};for(const m of [5,6,7]){const total=Object.values(p.cats[m]).reduce((a,b)=>a+b,0);s.catMonth[m]=Object.entries(p.cats[m]).map(([name,dt])=>({name,dt,share:total?dt/total*100:0})).sort((a,b)=>b.dt-a.dt)}const names=new Set([5,6,7].flatMap(m=>Object.keys(p.cats[m])));s.catComp=[...names].map(name=>({name,5:p.cats[5][name]||0,6:p.cats[6][name]||0,7:p.cats[7][name]||0,8:0}))}const total8=Object.values(p.cats[8]).reduce((a,b)=>a+b,0);if(total8>0){s.monthly=[...s.monthly.filter(x=>x.Tháng!==8),{Tháng:8,...p.rev[8]}];s.catMonth[8]=Object.entries(p.cats[8]).map(([name,dt])=>({name,dt,share:total8?dt/total8*100:0})).sort((a,b)=>b.dt-a.dt);const map=new Map((s.catComp||[]).map(x=>[x.name,x]));for(const [name,v] of Object.entries(p.cats[8])){if(!map.has(name))map.set(name,{name,5:0,6:0,7:0,8:0});map.get(name)[8]=v}s.catComp=[...map.values()]}s.sameOverall={};for(const m of [5,6,7,8])s.sameOverall[m]={Tháng:m,...p.rev[m]};s.lastProcessedAt=Math.max(...files.map(f=>f.time),Date.now());save(s);inject(s);return s}
async function reply(token,text){const r=await fetch('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+TOKEN},body:JSON.stringify({replyToken:token,messages:[{type:'text',text}]})});if(!r.ok)console.error(await r.text())}
async function download(id,dest){const r=await fetch('https://api-data.line.me/v2/bot/message/'+id+'/content',{headers:{Authorization:'Bearer '+TOKEN}});if(!r.ok)throw Error('Không tải được file');fs.writeFileSync(dest,Buffer.from(await r.arrayBuffer()))}
app.get('/',(q,s)=>s.send('LINE Bot is running'));app.get('/suc-khoe',(q,s)=>s.type('html').send(fs.readFileSync(HEALTH,'utf8')));
app.post('/webhook',express.raw({type:'application/json'}),async(req,res)=>{try{const body=req.body.toString(),sig=req.headers['x-line-signature'],expected=crypto.createHmac('sha256',SECRET||'').update(body).digest('base64');if(!SECRET||sig!==expected)return res.sendStatus(401);res.sendStatus(200);for(const e of JSON.parse(body).events||[]){if(e.message?.type==='file'){const safe=path.basename(e.message.fileName||'data.xlsx').replace(/[^\w.\- ]/g,'_');try{await download(e.message.id,path.join(UPLOADS,Date.now()+'_'+safe));await reply(e.replyToken,'📥 Đã nhận file.')}catch(x){await reply(e.replyToken,'❌ Không nhận được file.')}continue}if(e.message?.type!=='text')continue;const t=e.message.text.trim().toLowerCase().replace(/\s+/g,' ');if(t==='nạp dữ liệu sức khỏe'||t==='nap du lieu suc khoe'){try{ingest();await reply(e.replyToken,'✅ Đã nạp SỨC KHỎE\nhttps://ng-bot-c0im.onrender.com/suc-khoe')}catch(x){await reply(e.replyToken,'⚠️ '+x.message)}}else if(t==='bc sức khỏe'||t==='bc suc khoe'){await reply(e.replyToken,'📊 BC SỨC KHỎE\nhttps://ng-bot-c0im.onrender.com/suc-khoe')}else if(t==='nạp dữ liệu dt hôm nay'||t==='nap du lieu dt hom nay'){try{const f=uploads().at(-1);if(!f)throw Error('Chưa có file DT HÔM NAY');const a=read(f.path);let off=0,on=0,bills=0;for(const r of a){off+=num(r[key(r,['Doanh thu offline','Doanh thu Offline'])]);on+=num(r[key(r,['Doanh thu Online','Doanh thu online'])]);bills+=num(r[key(r,['Tổng số bill','Tổng bill','Bill'])])}fs.writeFileSync(DT,JSON.stringify({offline:off,online:on,bills,dt:off+on,updatedAt:new Date().toISOString()}));await reply(e.replyToken,'✅ Đã nạp DT HÔM NAY.')}catch(x){await reply(e.replyToken,'⚠️ '+x.message)}}}}catch(err){console.error(err)}});app.listen(PORT,()=>console.log('Clean LINE bot running'));