const fs=require('fs');
const target=require('path').join(__dirname,'server.js');
let s=fs.readFileSync(target,'utf8');
const cat=`function categories(rows){const r0=rows[0]||{};const kd=key(r0,['Ngày xuất','Ngày','Date'])||fuzzy(r0,/ngày.*(xuất|xuat)|date/);const kc=key(r0,['Ngành hàng BHX','Ngành hàng'])||fuzzy(r0,/ngành hàng|nganh hang/);const kr=key(r0,['Doanh thu'])||fuzzy(r0,/doanh thu/);const out={};for(const r of rows){const d=kd?date(r[kd]):null;if(!d)continue;const m=d.getMonth()+1;if(m<5||m>8)continue;const n=String(r[kc]||'Chưa phân loại').trim();if(/c\\.p\\b|c\\s*p\\b/i.test(n))continue;if(!out[n])out[n]={name:n,5:0,6:0,7:0,8:0};out[n][m]+=num(r[kr])}return Object.values(out)}`;
const fg=`function freshGroup(row,kp,kc){const p=String(kp?row[kp]:'').trim();const c=String(kc?row[kc]:'').trim();if(!p)return null;const all=(c+' '+p).toLowerCase();if(/c\\.p\\b|c\\s*p\\b/.test(all))return null;const cat=c.toLowerCase();if(cat){if(/bia|sữa|sua|nước|nuoc|kem|trứng|trung|bánh|banh|đông lạnh|dong lanh|hàng mát|hang mat|thức uống|thuc uong|đồ uống|do uong|chăm sóc|cham soc|hóa mỹ phẩm|hoa my pham/.test(cat))return null;if(/rau\\s*củ|rau\\s*cu|rau\\s*củ\\s*quả|rau\\s*cu\\s*qua|rau củ quả cl|rau cu qua cl/.test(cat))return'RAU CỦ';if(/thịt|thit/.test(cat))return'THỊT';if(/cá|ca|hải sản|hai san/.test(cat))return'CÁ / THỦY HẢI SẢN';if(/trái cây|trai cay/.test(cat))return'TRÁI CÂY';return null}const s=p.toLowerCase();if(/bia|sữa|sua|nước|nuoc|kem|trứng|trung|bánh|banh|đông lạnh|dong lanh|hàng mát|hang mat|thức uống|thuc uong/.test(s))return null;if(/thịt|thit|heo|bò|bo|gà|ga|sườn|suon|cánh gà|canh ga|đùi|dui|xương|xuong|chân giò|chan gio/.test(s))return'THỊT';if(/cá|\\bca\\b|hải sản|hai san|tôm|tom|mực|muc|cua|ghẹ|ghe|nghêu|ngheu|sò|so /.test(s))return'CÁ / THỦY HẢI SẢN';if(/trái cây|trai cay|dưa hấu|dua hau|táo|tao |nho |xoài|xoai|chuối|chuoi|thanh long|dưa lưới|dua luoi|kiwi|lê |le |cam |quýt|quyt|bưởi|buoi|mận|man |đào|dao |dâu|dau /.test(s))return'TRÁI CÂY';if(/rau|củ|cu |nấm|nam |bắp cải|bap cai|cải|cai |cà rốt|ca rot|hành|hanh |khoai|bắp mỹ|bap my|dưa leo|dua leo/.test(s))return'RAU CỦ';return null}`;
s=s.replace(/function categories\(rows\)\{[\s\S]*?\nfunction freshGroup/,cat+'\nfunction freshGroup');
s=s.replace(/function freshGroup\(row,kp,kc\)\{[\s\S]*?\nfunction fresh\(/,fg+'\nfunction fresh(');
fs.writeFileSync(target,s);
require('./server.js');
