const fs=require("fs"),path=require("path"),XLSX=require("xlsx");
const DIR=path.join(__dirname,"data","fresh");fs.mkdirSync(DIR,{recursive:true});
const XLS=path.join(DIR,"latest.xlsx"),HTML=path.join(DIR,"latest.html"),META=path.join(DIR,"latest.json"),PENDING=path.join(DIR,"pending.json");
const n=v=>{const x=Number(String(v??"").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0};
const money=v=>Math.round(v).toLocaleString("vi-VN")+"đ";
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function find(o,keys){for(const k of keys){const x=Object.keys(o).find(a=>a.toLowerCase().includes(k.toLowerCase()));if(x)return o[x]}return ""}
function cat(x){x=String(x||"").toLowerCase();if(x.includes("rau"))return"Rau củ";if(x.includes("trái")||x.includes("trai"))return"Trái cây";if(x.includes("thịt")||x.includes("thit"))return"Thịt";if(x.includes("thủy")||x.includes("thuy")||x.includes("hải")||x.includes("hai sản"))return"Thủy hải sản";if(x.includes("sữa")||x.includes("sua"))return"Sản phẩm từ sữa";if(x.includes("đông lạnh")||x.includes("dong lanh")||x.includes("hàng mát")||x.includes("hang mat")||x.includes("kem"))return"Đông mát";return""}
function parse(buf){const wb=XLSX.read(buf,{type:"buffer"});let rows=[];for(const ws of Object.values(wb.Sheets))rows.push(...XLSX.utils.sheet_to_json(ws,{defval:""}));const out=[];for(const r of rows){const ng=find(r,["ngành hàng","nganh hang","nhóm hàng"]);const c=cat(ng);if(!c)continue;const name=String(find(r,["tên sản phẩm","ten san pham","sản phẩm"])).trim();const code=String(find(r,["mã sản phẩm","ma san pham","mã hàng","ma hang"]));if(!name||/(^|[^a-z])c\.?\s*p\.?([^a-z]|$)/i.test(name+" "+code))continue;const sale=n(find(r,["doanh thu"])),mm=n(find(r,["mất mát kiểm kê","mat mat kiem ke"])),ncc=n(find(r,["hủy hao hụt ncc","huy hao hut ncc"])),ht=n(find(r,["hủy tồn","huy ton"])),qty=n(find(r,["tổng sl bán","tong sl ban"]));const unit=sale&&qty?sale/qty:0;const loss=(mm+ncc+ht)*unit;out.push({c,name,sale,loss,mm,ncc,ht,qty})}return out}
function build(rows,file){const total=rows.reduce((a,x)=>(a.sale+=x.sale,a.loss+=x.loss,a),{sale:0,loss:0});const groups={};for(const r of rows){const g=r.c.includes("sữa")||r.c==="Đông mát"?"ĐÔNG MÁT":"FRESH";(groups[g]??=[]).push(r)}const top=[...rows].sort((a,b)=>b.loss-a.loss).slice(0,15);const list=top.map((x,i)=>`<li><span>${i+1}. ${esc(x.name)}<small>SL hao hụt: ${Math.round(x.mm+x.ncc+x.ht).toLocaleString("vi-VN")}</small></span><b>${money(x.loss)}</b></li>`).join("");const cards=Object.entries(groups).map(([g,a])=>{const s=a.reduce((o,x)=>(o.sale+=x.sale,o.loss+=x.loss,o),{sale:0,loss:0});return`<section><h2>${g}<b>${money(s.loss)}</b></h2>${[...new Set(a.map(x=>x.c))].map(c=>{const z=a.filter(x=>x.c===c).reduce((o,x)=>o+x.loss,0);return`<div class="row"><span>${esc(c)}</span><b>${money(z)}</b></div>`}).join("")}</section>`}).join("");return`<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hao hụt Fresh & Đông mát</title><style>body{margin:0;background:#eef2ed;color:#16201a;font-family:Arial,sans-serif}.bao{max-width:660px;margin:auto;padding:18px 14px}h1{font-size:26px}section,.hero,ol{background:#fff;border:1px solid #d6ddd5;border-radius:14px;padding:16px;margin:14px 0}.hero b{font-size:32px;color:#c62828;display:block;margin:8px 0}.sub{color:#6a7a6e;font-size:13px}h2{display:flex;justify-content:space-between;color:#14432a;font-size:17px}.row,li{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px dashed #d6ddd5}.row:last-child,li:last-child{border:0}ol{list-style:none;padding:0 16px}li span{font-weight:600}small{display:block;color:#6a7a6e;margin-top:3px}.note{font-size:12px;color:#5c5636;background:#fffdf5;border:1px solid #ebdfb8;border-radius:12px;padding:14px;margin-top:16px}</style><main class="bao"><div class="sub">BC HAO HỤT · FILE MỚI NHẤT</div><h1>Hao hụt hàng Fresh<br>& Đông mát</h1><div class="hero"><span class="sub">Giá trị hao hụt ước tính</span><b>${money(total.loss)}</b><div class="sub">Doanh thu: ${money(total.sale)} · Tỷ lệ: ${total.sale?(total.loss/total.sale*100).toFixed(2):"0.00"}%</div></div>${cards}<h3>15 mặt hàng rò rỉ nhiều nhất</h3><ol>${list||"<li>Không có dữ liệu phù hợp</li>"}</ol><div class="note">Đã bỏ FMCG. Đã loại mã/tên C.P. Giá trị hao hụt được ước tính từ đơn giá bình quân doanh thu ÷ sản lượng bán khi dữ liệu nguồn không có cột thành tiền hao hụt.<br>File: ${esc(file)}</div></main></html>`}
function save(buf,file){const rows=parse(buf);if(!rows.length)throw Error("Không nhận diện được dữ liệu FRESH/ĐÔNG MÁT trong file");const html=build(rows,file);fs.writeFileSync(XLS,buf);fs.writeFileSync(HTML,html);const total=rows.reduce((a,x)=>(a.sale+=x.sale,a.loss+=x.loss,a),{sale:0,loss:0});const meta={fileName:file,updatedAt:new Date().toISOString(),sale:total.sale,loss:total.loss,pct:total.sale?total.loss/total.sale*100:0,rows:rows.length};fs.writeFileSync(META,JSON.stringify(meta,null,2));return meta}
function get(){try{return JSON.parse(fs.readFileSync(META,"utf8"))}catch{return null}}function beginUpload(){fs.writeFileSync(PENDING,JSON.stringify({active:true,startedAt:new Date().toISOString()}))}function isPending(){try{return JSON.parse(fs.readFileSync(PENDING,"utf8")).active===true}catch{return false}}function finishUpload(){try{fs.unlinkSync(PENDING)}catch{}}function exists(){return fs.existsSync(XLS)&&fs.existsSync(HTML)}function page(){return fs.readFileSync(HTML,"utf8")}
module.exports={save,get,beginUpload,isPending,finishUpload,exists,page};