const express=require("express");const crypto=require("crypto");const fs=require("fs");const path=require("path");const XLSX=require("xlsx");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.LINE_CHANNEL_SECRET,TOKEN=process.env.LINE_CHANNEL_ACCESS_TOKEN;
const DATA=path.join(__dirname,"data"),HF=path.join(DATA,"health_uploads"),HEALTH=path.join(__dirname,"health.html"),REPORT=path.join(__dirname,"report.html"),DT=path.join(DATA,"DT_HOM_NAY.json"),HEALTH_LOCK=path.join(DATA,"health_locked.json");fs.mkdirSync(HF,{recursive:true});
const targets=new Set((process.env.LINE_GROUP_IDS||process.env.LINE_GROUP_ID||process.env.LINE_TARGET_ID||process.env.LINE_CHAT_ID||"").split(",").map(x=>x.trim()).filter(Boolean));
const money=n=>Math.round(Number(n)||0).toLocaleString("vi-VN")+" đ";const num=v=>{if(typeof v==='number')return isFinite(v)?v:0;const n=Number(String(v??'').replace(/[^\d.-]/g,''));return isNaN(n)?0:n};
function date(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==='number'){const x=XLSX.SSF.parse_date_code(v);return x?new Date(x.y,x.m-1,x.d):null}const s=String(v||'').trim(),m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const d=new Date(s);return isNaN(d)?null:d}
const keys=r=>r.length?Object.keys(r[0]):[];function key(ks,a){for(const c of a){const x=ks.find(k=>String(k).trim().toLowerCase()===c.toLowerCase());if(x)return x}return null}
function read(f){const wb=XLSX.readFile(f,{cellDates:true});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:null,raw:true})}
function classify(r){const k=keys(r);return {rev:!!(key(k,['Ngày','Date','Ngày bán'])&&(key(k,['Doanh thu offline','Doanh thu Offline'])||key(k,['Doanh thu Online']))),cat:!!(key(k,['Ngành hàng BHX','Ngành hàng'])&&key(k,['Doanh thu']))}}
function buildRev(r){const k=keys(r),kd=key(k,['Ngày','Date','Ngày bán']),ko=key(k,['Doanh thu offline','Doanh thu Offline']),kn=key(k,['Doanh thu Online','Doanh thu online']),kb=key(k,['Tổng số bill','Tổng bill','Bill']),kc=key(k,['Mã siêu thị','Mã ST']),ks=key(k,['Tên siêu thị','Siêu thị','Tên ST']);const monthly=[5,6,7,8].map(m=>({Tháng:m,offline:0,online:0,bills:0,dt:0})),daily=[],stores={};for(const x of r){const d=date(x[kd]);if(!d||![8].includes(d.getMonth()+1))continue;const o=num(x[ko]),n=num(x[kn]),b=num(x[kb]),z=monthly[3];z.offline+=o;z.online+=n;z.bills+=b;z.dt+=o+n;const dk=d.toISOString().slice(0,10);let q=daily.find(y=>y.date===dk);if(!q){q={date:String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0'),month:8,dt:0};daily.push(q)}q.dt+=o+n;const id=String(x[kc]||'')+'|'+String(x[ks]||'');if(!stores[id])stores[id]={"Mã siêu thị":x[kc]||'',"Tên siêu thị":x[ks]||x[kc]||'',offline:0,online:0,bills:0,dt:0};stores[id].offline+=o;stores[id].online+=n;stores[id].bills+=b;stores[id].dt+=o+n}return {monthly,daily,sameOverall:{8:{offline:monthly[3].offline,online:monthly[3].online,bills:monthly[3].bills,dt:monthly[3].dt}},stores:Object.values(stores).sort((a,b)=>b.dt-a.dt)}}
function buildCat(r){const k=keys(r),kd=key(k,['Ngày xuất','Ngày','Date']),kc=key(k,['Ngành hàng BHX','Ngành hàng']),kr=key(k,['Doanh thu']),rows=[];for(const x of r){const d=date(x[kd]);if(!d||d.getMonth()+1!==8)continue;rows.push(x)}const cm={8:[]},comp={},same={8:{}};for(const x of rows){const c=String(x[kc]||'Chưa phân loại').trim(),v=num(x[kr]);if(!comp[c])comp[c]={name:c,'8':0};comp[c]['8']+=v;if(d<=11)same[8][c]=(same[8][c]||0)+v}cm[8]=Object.values(comp).map(x=>({name:x.name,dt:x['8'],share:0})).sort((a,b)=>b.dt-a.dt);const t=cm[8].reduce((s,x)=>s+x.dt,0);cm[8].forEach(x=>x.share=t?x.dt/t*100:0);return {catMonth:cm,catComp:Object.values(comp),sameCat:same}}
function loadHealth(){try{return JSON.parse(fs.readFileSync(HEALTH_LOCK,'utf8'))}catch(e){return {monthly:[],daily:[],sameOverall:{},catMonth:{},catComp:[],sameCat:{},stores:[]}}}
function saveHealth(d){fs.writeFileSync(HEALTH_LOCK,JSON.stringify(d));}
function updateHealth(d){let html=fs.readFileSync(HEALTH,'utf8'),a=html.indexOf('const monthly='),b=html.indexOf('let selected=8;',a);if(a<0||b<0)throw Error('health.html sai mẫu');const vars='const monthly='+JSON.stringify(d.monthly||[])+ ';const daily='+JSON.stringify(d.daily||[])+ ';const sameOverall='+JSON.stringify(d.sameOverall||{})+ ';const catMonth='+JSON.stringify(d.catMonth||{})+ ';const catComp='+JSON.stringify(d.catComp||[])+ ';const sameCat='+JSON.stringify(d.sameCat||{})+ ';const stores='+JSON.stringify(d.stores||[])+ ';';html=html.slice(0,a)+vars+html.slice(b);fs.writeFileSync(HEALTH+'.tmp',html);fs.renameSync(HEALTH+'.tmp',HEALTH)}
function uploads(){return fs.readdirSync(HF).filter(f=>/\.(xlsx|xls|csv)$/i.test(f)).map(f=>({f,p:path.join(HF,f),t:fs.statSync(path.join(HF,f)).mtimeMs})).sort((a,b)=>b.t-a.t)}
function generateHealth(){const old=loadHealth(),files=uploads(),newData={...old};for(const z of files.slice(0,10)){try{const r=read(z.p),c=classify(r);if(c.rev)newData.rev=buildRev(r);if(c.cat)newData.cat=buildCat(r)}catch(e){console.error(e)}}if(!newData.rev&&!newData.cat)throw Error('Chưa có file dữ liệu sức khỏe');if(newData.rev){newData.monthly=(old.monthly||[]).map(x=>x.Tháng===8?newData.rev.monthly[3]:x);if(!newData.monthly.some(x=>x.Tháng===8))newData.monthly.push(newData.rev.monthly[3]);newData.daily=newData.rev.daily;newData.sameOverall={...(old.sameOverall||{}),...(newData.rev.sameOverall||{})};newData.stores=newData.rev.stores}if(newData.cat){newData.catMonth={...(old.catMonth||{}),...(newData.cat.catMonth||{})};newData.catComp=newData.cat.catComp;newData.sameCat={...(old.sameCat||{}),...(newData.cat.sameCat||{})} }delete newData.rev;delete newData.cat;saveHealth(newData);updateHealth(newData)}
async function reply(t,msg){const r=await fetch('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+TOKEN},body:JSON.stringify({replyToken:t,messages:[{type:'text',text:msg}]})});if(!r.ok)console.error(await r.text())}
async function content(id,dest){const r=await fetch('https://api-data.line.me/v2/bot/message/'+id+'/content',{headers:{Authorization:'Bearer '+TOKEN}});if(!r.ok)throw Error('LINE '+r.status);fs.writeFileSync(dest,Buffer.from(await r.arrayBuffer()))}
function oldReport(){try{let h=fs.readFileSync(REPORT,'utf8'),d=JSON.parse(fs.readFileSync(DT));const total=num(d.doanh_thu_offline)+num(d.doanh_thu_online);h=h.replace(/19\.042\.795 đ/g,money(total)).replace(/13\.987\.493/g,Math.round(num(d.doanh_thu_offline)).toLocaleString('vi-VN')).replace(/5\.055\.302/g,Math.round(num(d.doanh_thu_online)).toLocaleString('vi-VN')).replace(/148/g,String(d.tong_bill));return h}catch(e){return 'Chưa có DATA'}}
app.get('/',(q,s)=>s.send('LINE Bot is running!'));app.get('/report',(q,s)=>s.type('html').send(oldReport()));app.get('/suc-khoe',(q,s)=>s.type('html').send(fs.readFileSync(HEALTH,'utf8')));
app.post('/webhook',express.raw({type:'application/json'}),async(req,res)=>{try{const body=req.body.toString(),sig=req.headers['x-line-signature'],exp=crypto.createHmac('sha256',SECRET||'').update(body).digest('base64');if(!SECRET||sig!==exp)return res.sendStatus(401);res.sendStatus(200);for(const e of JSON.parse(body).events||[]){if(e.source?.groupId)targets.add(e.source.groupId);if(e.message?.type==='file'){const name=path.basename(e.message.fileName||'data.xlsx').replace(/[^\w.\- ]/g,'_');try{await content(e.message.id,path.join(HF,Date.now()+'_'+name));await reply(e.replyToken,'📥 Đã nhận file.\nNhắn lệnh tương ứng: NẠP DỮ LIỆU DT HÔM NAY hoặc NẠP DỮ LIỆU SỨC KHỎE')}catch(x){await reply(e.replyToken,'❌ Không tải được file. Anh gửi lại nhé.')}continue}if(e.message?.type!=='text')continue;const t=e.message.text.toLowerCase().replace(/\s+/g,' ').trim();if(t==='bc sức khỏe'||t==='bc suc khoe'){await reply(e.replyToken,'📊 BC SỨC KHỎE\nhttps://ng-bot-c0im.onrender.com/suc-khoe')}else if(t.includes('nạp dữ liệu sức khỏe')||t.includes('nap du lieu suc khoe')){try{generateHealth();await reply(e.replyToken,'✅ Đã nạp dữ liệu SỨC KHỎE.\n📊 https://ng-bot-c0im.onrender.com/suc-khoe')}catch(x){console.error(x);await reply(e.replyToken,'⚠️ '+x.message)}}else if(t.includes('nạp dữ liệu dt hôm nay')||t.includes('nap du lieu dt hom nay')){try{const fsu=uploads()[0];if(!fsu)throw Error('Chưa có file DT HÔM NAY');const r=read(fsu.p);const rev=buildRev(r);const z=rev.monthly[3];fs.writeFileSync(DT,JSON.stringify({doanh_thu_offline:z.offline,doanh_thu_online:z.online,tong_bill:z.bills,ten_sieu_thi:rev.stores[0]?.['Tên siêu thị']||''}));await reply(e.replyToken,'✅ Đã nạp dữ liệu DT HÔM NAY.\nNhắn BC để xem báo cáo.')}catch(x){await reply(e.replyToken,'⚠️ '+x.message)}}else if(t.includes('dt hôm nay')||t.includes('dt hom nay')){let d=loadData();const total=d?num(d.doanh_thu_offline)+num(d.doanh_thu_online):0;await reply(e.replyToken,'📊 DT HÔM NAY\n\n🏪 '+(d?.ten_sieu_thi||'chưa có DATA')+'\n💰 Tổng DT: '+money(total)+'\n🏪 Offline: '+money(d?.doanh_thu_offline)+'\n📱 Online: '+money(d?.doanh_thu_online)+'\n🧾 Bill: '+(d?.tong_bill||0))}}}catch(err){console.error('WEBHOOK',err)}});
function loadData(){try{return JSON.parse(fs.readFileSync(DT,'utf8'))}catch(e){return null}}
app.listen(PORT,()=>console.log('LINE Bot running '+PORT));
