const express=require("express");const crypto=require("crypto");const fs=require("fs");const path=require("path");
const app=express(),PORT=process.env.PORT||3000,CHANNEL_SECRET=process.env.LINE_CHANNEL_SECRET,ACCESS_TOKEN=process.env.LINE_CHANNEL_ACCESS_TOKEN;
const REPORT_HTML=path.join(__dirname,"report.html"),DATA_DIR=path.join(__dirname,"data");
function money(n){return Math.round(n||0).toLocaleString("vi-VN")+" đ"}
function loadData(){try{const files=fs.readdirSync(DATA_DIR).filter(f=>f.endsWith(".json"));const rows=files.map(f=>JSON.parse(fs.readFileSync(path.join(DATA_DIR,f),"utf8"))).filter(x=>x&&x.ngay);return rows.sort((a,b)=>String(b.ngay).localeCompare(String(a.ngay)))[0]||null}catch(e){console.error("DATA error",e);return null}}
function latestReportHtml(){let html=fs.readFileSync(REPORT_HTML,"utf8"),d=loadData();if(d){const total=Number(d.doanh_thu_offline||0)+Number(d.doanh_thu_online||0),b=Number(d.tong_bill||0),avg=b?total/b:0;const r=(a,v)=>html=html.split(a).join(v);["19.042.795 đ","13.208.925 đ","13.765.038 đ"].forEach(x=>r(x,money(total)));["13.987.493","8.153.623"].forEach(x=>r(x,Math.round(d.doanh_thu_offline||0).toLocaleString("vi-VN")));r("5.055.302",Math.round(d.doanh_thu_online||0).toLocaleString("vi-VN"));["148","96","97"].forEach(x=>r(x,String(b)));r("128.668 đ",money(avg));}return html}
async function replyLine(token,messages){const r=await fetch("https://api.line.me/v2/bot/message/reply",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+ACCESS_TOKEN},body:JSON.stringify({replyToken:token,messages})});if(!r.ok)console.error("LINE",r.status,await r.text())}
app.get("/",(q,s)=>s.send("LINE Bot is running!"));app.get("/report",(q,s)=>s.type("html").send(latestReportHtml()));
app.post("/webhook",express.raw({type:"application/json"}),async(req,res)=>{try{const body=req.body.toString("utf8"),sig=req.headers["x-line-signature"],expected=crypto.createHmac("sha256",CHANNEL_SECRET||"").update(body).digest("base64");if(!CHANNEL_SECRET||!ACCESS_TOKEN||sig!==expected)return res.sendStatus(401);for(const e of(JSON.parse(body).events||[])){if(e.type!=="message"||e.message?.type!=="text"||!e.replyToken)continue;const t=e.message.text.toLowerCase().replace(/\s+/g," ").trim();if(t.includes("dt hôm nay")){const d=loadData(),total=d?Number(d.doanh_thu_offline||0)+Number(d.doanh_thu_online||0):0,b=d?.tong_bill||0;await replyLine(e.replyToken,[{type:"text",text:`📊 DT HÔM NAY\n\n🏪 ${d?.ten_sieu_thi||"chưa có DATA"}\n💰 Tổng DT: ${money(total)}\n🏪 Offline: ${money(d?.doanh_thu_offline)}\n📱 Online: ${money(d?.doanh_thu_online)}\n🧾 Bill: ${b}\n🎯 Bill BQ: ${money(b?total/b:0)}`}])}else await replyLine(e.replyToken,[{type:"text",text:"Anh gõ DT HÔM NAY để nhận báo cáo doanh thu hôm nay."}])}res.sendStatus(200)}catch(e){console.error("Webhook",e);res.sendStatus(500)}});app.listen(PORT,()=>console.log(`LINE Bot running on ${PORT}`));
