// Local POS export worker. Requires Chrome started with CDP on 127.0.0.1:9222.
// Flow: day 01 -> today -> store 28717 -> Export Excel -> Export History -> View Report -> wait "Đã xuất xong" -> Download.
const puppeteer=require('puppeteer');const fs=require('fs');const path=require('path');
const CDP=process.env.POS_CDP_URL||'http://127.0.0.1:9222';const STORE=process.env.POS_STORE||'28717';const REPORT=process.env.POS_REPORT||'336';const OUT=path.resolve(process.env.POS_DOWNLOAD_DIR||'./data/pos');fs.mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const norm=s=>String(s||'').replace(/\s+/g,' ').trim().toLowerCase();
function vnDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}function firstDay(){const d=vnDate();return d.slice(0,8)+'01'}
async function clickText(page,needles){return page.evaluate(ns=>{const n=s=>String(s||'').replace(/\s+/g,' ').trim().toLowerCase();const els=[...document.querySelectorAll('button,a,[role="button"],input[type="button"],input[type="submit"]')];for(const x of ns){const e=els.find(e=>n(e.innerText||e.value||e.getAttribute('aria-label')||e.title).includes(n(x)));if(e){e.click();return true}}return false},Array.isArray(needles)?needles:[needles])}
async function dump(page){const text=await page.evaluate(()=>document.body?.innerText||'');fs.writeFileSync(path.join(OUT,'pos_dom.txt'),text);return text}
async function setInputNear(page,labels,value){return page.evaluate(({labels,value})=>{const n=s=>String(s||'').replace(/\s+/g,' ').trim().toLowerCase();for(const l of [...document.querySelectorAll('label,span,div')]){if(!labels.some(x=>n(l.innerText).includes(n(x))))continue;const root=l.closest('.form-group,.form-item,.ant-form-item,.el-form-item,.row')||l.parentElement;const i=root?.querySelector('input');if(i){const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;set?.call(i,value);i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}));i.blur();return true}}return false},{labels,value})}
async function chooseStore(page){const opened=await clickText(page,['Siêu thị','Cửa hàng','Store']);if(opened)await sleep(500);return page.evaluate(store=>{const n=s=>String(s||'').replace(/\s+/g,' ').trim();const exact=[...document.querySelectorAll('button,[role="option"],li,div')].find(e=>n(e.innerText)===store);if(exact){exact.click();return true}const i=[...document.querySelectorAll('input')].find(x=>/siêu thị|cửa hàng|store/i.test(x.placeholder||x.getAttribute('aria-label')||''));if(i){const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;set?.call(i,store);i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}));return true}return false},STORE)}
async function main(){const browser=await puppeteer.connect({browserURL:CDP,defaultViewport:null});const pages=await browser.pages();const page=pages.find(p=>/pos\.bachhoaxanh\.com/i.test(p.url()))||pages[0];if(!page)throw Error('Không tìm thấy tab Chrome');await page.bringToFront();console.log('Attached:',page.url());try{if(!/pos\.bachhoaxanh\.com/i.test(page.url()))await page.goto(`https://pos.bachhoaxanh.com/reports/home/dashboard/${REPORT}`,{waitUntil:'domcontentloaded',timeout:60000});const from=firstDay(),to=vnDate();console.log(`Flow: ${from} -> ${to} | store ${STORE} | report ${REPORT}`);const a=await setInputNear(page,['từ ngày','from date'],from),b=await setInputNear(page,['đến ngày','to date'],to);if(!a||!b){await dump(page);throw Error('Không tìm thấy ô ngày; đã lưu data/pos/pos_dom.txt')}if(!await chooseStore(page)){await dump(page);throw Error(`Không chọn được siêu thị ${STORE}; đã lưu DOM text`)}await sleep(700);if(!await clickText(page,['Xuất Excel','Xuất file Excel','Export Excel'])){await dump(page);throw Error('Không tìm thấy Xuất Excel')}console.log('1/5 Đã Xuất Excel');await sleep(1500);if(!await clickText(page,['Lịch sử xuất Excel','Lịch sử xuất file','Lịch sử xuất'])){await dump(page);throw Error('Không tìm thấy Lịch sử xuất Excel')}console.log('2/5 Đã mở Lịch sử xuất Excel');await sleep(1000);if(!await clickText(page,['Xem báo cáo'])){await dump(page);throw Error('Không tìm thấy Xem báo cáo')}console.log('3/5 Đã bấm Xem báo cáo');let ready=false;for(let i=0;i<72;i++){const t=norm(await page.evaluate(()=>document.body?.innerText||''));if(t.includes('đã xuất xong')||t.includes('da xuat xong')){ready=true;break}await sleep(2500)}if(!ready){await dump(page);throw Error('Chưa thấy trạng thái Đã xuất xong sau 3 phút')}console.log('4/5 Trạng thái Đã xuất xong');const cdp=await page.target().createCDPSession();await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:OUT});const before=new Set(fs.readdirSync(OUT));if(!await clickText(page,['Tải file','Tải xuống','Download'])){await dump(page);throw Error('Không tìm thấy Tải file')}for(let i=0;i<60;i++){const files=fs.readdirSync(OUT).filter(f=>!f.endsWith('.crdownload')&&!before.has(f));if(files.length){console.log('5/5 DOWNLOAD_OK:',path.join(OUT,files[0]));return}await sleep(1000)}throw Error('Đã bấm Tải file nhưng chưa thấy file tải xuống')}finally{await browser.disconnect()}}main().catch(e=>{console.error('POS EXPORT ERROR:',e.stack||e);process.exitCode=1})
