const express=require('express');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const XLSX=require('xlsx');

const app=express();
const PORT=process.env.PORT||3000;
const SECRET=process.env.LINE_CHANNEL_SECRET;
const TOKEN=process.env.LINE_CHANNEL_ACCESS_TOKEN;
const DATA=path.join(__dirname,'data');
const INBOX=path.join(DATA,'health_uploads');
const HEALTH=path.join(__dirname,'health.html');
const DT=path.join(DATA,'DT_HOM_NAY.json');
const STATE=path.join(DATA,'health_locked.json');
fs.mkdirSync(INBOX,{recursive:true});

const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const n=Number(String(v??'').replace(/[^\d.-]/g,''));return Number.isFinite(n)?n:0};
function date(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==='number'){const x=XLSX.SSF.parse_date_code(v);return x?new Date(x.y,x.m-1,x.d):null}const s=String(v||'').trim();let m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const d=new Date(s);return isNaN(d)?null:d}
function key(r,names){const ks=Object.keys(r||{});for(const n of names){const k=ks.find(x=>String(x).trim().toLowerCase()===n.toLowerCase());if(k)return k}return null}
function read(file){const wb=XLSX.readFile(file,{cellDates:true});let rows=[];for(const sn of wb.SheetNames)rows.push(...XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:null,raw:true}));return rows}
function files(){return fs.readdirSync(INBOX).filter(f=>/\.(xlsx|xls|csv)$/i.test(f)).map(f=>({name:f,path:path.join(INBOX,f),time:fs.statSync(path.join(INBOX,f)).mtimeMs})).sort((a,b)=>b.time-a.time)}
function kind(rows){const r=rows.find(x=>x&&Object.keys(x).length);if(!r)return 'unknown';const k=Object.keys(r);const rev=!!(key(r,['Ngày','Ngày bán','Date'])&&(key(r,['Doanh thu offline','Doanh thu Offline'])||key(r,['Doanh thu Online','Doanh thu online'])));const cat=!!(key(r,['Ngày xuất','Ngày','Date'])&&key(r,['Ngành hàng BHX','Ngành hàng'])&&key(r,['Doanh thu']));const fresh=!!(key(r,['Tên sản phẩm','Tên SP','Sản phẩm'])&&(key(r,['Tổng SL bán','SL bán'])||key(r,['SL bán']))&&(key(r,['SL mất mát kiểm kê','SL mất mát','Mất mát'])||key(r,['SL hủy tồn','SL hủy','Hủy'])));return rev?'revenue':cat?'category':fresh?'fresh':'unknown'}
function revenue(rows){const kd=key(rows[0]||{},['Ngày','Ngày bán','Date']);const ko=key(rows[0]||{},['Doanh thu offline','Doanh thu Offline']);const kn=key(rows[0]||{},['Doanh thu Online','Doanh thu online']);const kb=key(rows[0]||{},['Tổng số bill','Tổng bill','Bill']);let out={};for(const r of rows){const d=kd?date(r[kd]):null;if(!d)continue;const ds=d.toISOString().slice(0,10);if(!out[ds])out[ds]={date:ds,offline:0,online:0,bills:0};out[ds].offline+=num(ko?r[ko]:0);out[ds].online+=num(kn?r[kn]:0);out[ds].bills+=num(kb?r[kb]:0)}return Object.values(out).sort((a,b)=>a.date.localeCompare(b.date))}
function categories(rows){const r0=rows[0]||{};const kd=key(r0,['Ngày xuất','Ngày','Date']);const kc=key(r0,['Ngành hàng BHX','Ngành hàng']);const kr=key(r0,['Doanh thu']);const out={};for(const r of rows){const d=kd?date(r[kd]):null;if(!d)continue;const m=d.getMonth()+1;if(m<5||m>8)continue;const n=String(r[kc]||'Chưa phân loại').trim();if(!out[n])out[n]={name:n,5:0,6:0,7:0,8:0};out[n][m]+=num(r[kr])}return Object.values(out)}
function fresh(rows){const r0=rows[0]||{};const kp=key(r0,['Tên sản phẩm','Tên SP','Sản phẩm']);const ks=key(r0,['Tổng SL bán','SL bán']);const km=key(r0,['SL mất mát kiểm kê','SL mất mát','Mất mát']);const kh=key(r0,['SL hủy tồn','SL hủy','Hủy']);const kg=key(r0,['Giá trị giảm giá','Giảm giá','% giảm giá']);const out=[];for(const r of rows){const p=String(r[kp]||'').trim();if(!p)continue;out.push({san_pham:p,sl_ban:num(ks?r[ks]:0),mat_mat:num(km?r[km]:0),huy:num(kh?r[kh]:0),giam_gia:kg?r[kg]:0})}return out}
function load(){try{return JSON.parse(fs.readFileSync(STATE,'utf8'))}catch{return{locked:true,monthly:[],catMonth:{5:[],6:[],7:[],8:[]},catComp:[],sameOverall:{},fresh:[]}}}
function save(x){fs.writeFileSync(STATE,JSON.stringify(x))}
function updatePage(s){let h=fs.readFileSync(HEALTH,'utf8');const a=h.indexOf('const monthly=');const b=h.indexOf('let selected=8;',a);if(a<0||b<0)throw Error('health.html sai mẫu');const vars='const monthly='+JSON.stringify(s.monthly||[])+';const daily='+JSON.stringify(s.daily||[])+';const sameOverall='+JSON.stringify(s.sameOverall||{})+';const catMonth='+JSON.stringify(s.catMonth||{})+';const catComp='+JSON.stringify(s.catComp||[])+';const sameCat='+JSON.stringify(s.sameCat||{})+';const stores=[];';fs.writeFileSync(HEALTH,h.slice(0,a)+vars+h.slice(b))}
function ingestHealth(){const fsx=files();if(fsx.length<3)throw Error('Cần đủ 3 file SỨC KHỎE: 2 file T8 + 1 file FRESH');let revFile=null,catFile=null,freshFile=null;for(const f of fsx){try{const rows=read(f.path);const t=kind(rows);if(t==='revenue'&&!revFile)revFile={f,rows};else if(t==='category'&&!catFile)catFile={f,rows};else if(t==='fresh'&&!freshFile)freshFile={f,rows}}catch(e){console.error('READ',f.name,e)}}if(!revFile||!catFile||!freshFile)throw Error('Chưa nhận đủ đúng 3 loại file: doanh thu T8, ngành hàng T8 và FRESH');const old=load();const daily=revenue(revFile.rows);const byMonth={};for(const x of daily){const m=+x.date.slice(5,7);if(!byMonth[m])byMonth[m]={Tháng:m,offline:0,online:0,bills:0,dt:0};byMonth[m].offline+=x.offline;byMonth[m].online+=x.online;byMonth[m].bills+=x.bills;byMonth[m].dt+=x.offline+x.online}const cats=categories(catFile.rows);const catMonth={5:[],6:[],7:[],8:[]};for(const m of [5,6,7,8]){const a=cats.map(x=>({name:x.name,dt:x[m]||0})).filter(x=>x.dt>0).sort((a,b)=>b.dt-a.dt);const total=a.reduce((s,x)=>s+x.dt,0);a.forEach(x=>x.share=total?x.dt/total*100:0);catMonth[m]=a}const state={...old,locked:true,months_locked:[5,6,7],monthly:[5,6,7,8].map(m=>byMonth[m]||{Tháng:m,offline:0,online:0,bills:0,dt:0}),daily,catMonth,catComp:cats,fresh:fresh(freshFile.rows),freshFile:freshFile.f.name,lastUpdated:new Date().toISOString()};save(state);updatePage(state);return state}
async function reply(token,text){const r=await fetch('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+TOKEN},body:JSON.stringify({replyToken:token,messages:[{type:'text',text}]})});if(!r.ok)console.error('LINE_REPLY',await r.text())}
async function download(id,dest){const r=await fetch('https://api-data.line.me/v2/bot/message/'+id+'/content',{headers:{Authorization:'Bearer '+TOKEN}});if(!r.ok)throw Error('Không tải được file');fs.writeFileSync(dest,Buffer.from(await r.arrayBuffer()))}
app.get('/',(q,s)=>s.send('LINE Bot is running'));
app.get('/suc-khoe',(q,s)=>s.set('Cache-Control','no-store').type('html').send(fs.readFileSync(HEALTH,'utf8')));
app.post('/webhook',express.raw({type:'application/json'}),async(req,res)=>{try{const body=req.body.toString();const sig=req.headers['x-line-signature'];const expected=crypto.createHmac('sha256',SECRET||'').update(body).digest('base64');if(!SECRET||sig!==expected)return res.sendStatus(401);res.sendStatus(200);for(const e of JSON.parse(body).events||[]){try{if(e.message?.type==='file'){const safe=path.basename(e.message.fileName||'data.xlsx').replace(/[^\w.\- ]/g,'_');await download(e.message.id,path.join(INBOX,Date.now()+'_'+safe));await reply(e.replyToken,'📥 Đã nhận file vào KHO DATA.\nKhông cần đăng ký nhóm.');continue}if(e.message?.type!=='text')continue;const t=e.message.text.trim().toLowerCase().replace(/\s+/g,' ');if(t==='nạp dữ liệu sức khỏe'||t==='nap du lieu suc khoe'){ingestHealth();await reply(e.replyToken,'✅ ĐÃ NẠP ĐỦ 3 FILE SỨC KHỎE\n📊 BC SỨC KHỎE: https://ng-bot-c0im.onrender.com/suc-khoe');continue}if(t==='bc sức khỏe'||t==='bc suc khoe'){await reply(e.replyToken,'📊 BC SỨC KHỎE\nhttps://ng-bot-c0im.onrender.com/suc-khoe');continue}if(t==='nạp dữ liệu dt hôm nay'||t==='nap du lieu dt hom nay'||t==='nạp dữ liệu doanh thu'||t==='nap du lieu doanh thu'){const fsx=files()[0];if(!fsx)throw Error('Chưa có file doanh thu');const rows=read(fsx.path);if(kind(rows)!=='revenue')throw Error('File mới nhất không phải file doanh thu');const daily=revenue(rows);const today=new Date().toISOString().slice(0,10);const same=daily.filter(x=>x.date===today);const a=same.length?same:daily.slice(-1);const o=a.reduce((s,x)=>s+x.offline,0),n=a.reduce((s,x)=>s+x.online,0),b=a.reduce((s,x)=>s+x.bills,0);const result={ngay:a[0]?.date||today,offline:o,online:n,dt:o+n,bills:b,updatedAt:new Date().toISOString()};fs.writeFileSync(DT,JSON.stringify(result));await reply(e.replyToken,'✅ ĐÃ NẠP DT HÔM NAY\n📅 '+result.ngay+'\n💰 DT: '+Math.round(result.dt).toLocaleString('vi-VN')+' đ\n🧾 Bill: '+result.bills);continue}}catch(err){console.error('EVENT',err);if(e.replyToken)await reply(e.replyToken,'⚠️ '+err.message)}}}catch(err){console.error('WEBHOOK',err)}});
app.listen(PORT,()=>console.log('LINE Bot running '+PORT));