const express=require("express"),crypto=require("crypto"),fs=require("fs"),path=require("path"),XLSX=require("xlsx"),puppeteer=require("puppeteer");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.LINE_CHANNEL_SECRET,TOKEN=process.env.LINE_CHANNEL_ACCESS_TOKEN;
const DATA=path.join(__dirname,"data"),INBOX=path.join(DATA,"health_uploads"),LOCK=path.join(DATA,"health_locked.json"),HEALTH=path.join(__dirname,"health.html"),DT=path.join(DATA,"DT_HOM_NAY.json"),CFG=path.join(DATA,"line_groups.json");fs.mkdirSync(INBOX,{recursive:true});
const num=v=>{if(typeof v==="number")return Number.isFinite(v)?v:0;const n=Number(String(v??"").replace(/[^\d.-]/g,""));return Number.isFinite(n)?n:0};
function date(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==="number"){const x=XLSX.SSF.parse_date_code(v);return x?new Date(x.y,x.m-1,x.d):null}const s=String(v||"").trim(),m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const d=new Date(s);return isNaN(d)?null:d}
function key(keys,names){for(const n of names){const k=keys.find(x=>String(x).trim().toLowerCase()===n.toLowerCase());if(k)return k}return null}
function read(f){const w=XLSX.readFile(f,{cellDates:true});return XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:null,raw:true})}
function kind(f){const r=read(f),k=r.length?Object.keys(r[0]):[];return{r,k,rev:!!(key(k,["Ngày"])&&key(k,["Doanh thu offline","Doanh thu Offline"])),cat:!!(key(k,["Ngày xuất"])&&key(k,["Ngành hàng BHX","Ngành hàng"])&&key(k,["Doanh thu"]))}}
function revenue(r,k){const kd=key(k,["Ngày"]),ko=key(k,["Doanh thu offline","Doanh thu Offline"]),kn=key(k,["Doanh thu Online","Doanh thu online"]),kb=key(k,["Tổng số bill","Tổng bill","Bill"]),monthly=[5,6,7,8].map(m=>({Tháng:m,offline:0,online:0,bills:0,dt:0})),sameOverall={},daily=[];for(const x of r){const d=date(x[kd]);if(!d)continue;const m=d.getMonth()+1;if(m<5||m>8)continue;const o=num(x[ko]),n=num(x[kn]),b=num(x[kb]),z=monthly[m-5];z.offline+=o;z.online+=n;z.bills+=b;z.dt+=o+n;if(d.getDate()<=11){const s=sameOverall[String(m)]||(sameOverall[String(m)]={offline:0,online:0,bills:0,dt:0});s.offline+=o;s.online+=n;s.bills+=b;s.dt+=o+n}if(m===8){const ds=d.toISOString().slice(0,10);let q=daily.find(y=>y.date===ds);if(!q){q={date:ds,month:8,dt:0};daily.push(q)}q.dt+=o+n}}return{monthly,sameOverall,daily}}
function categories(r,k){const kd=key(k,["Ngày xuất"]),kc=key(k,["Ngành hàng BHX","Ngành hàng"]),kr=key(k,["Doanh thu"]),catMonth={"5":[],"6":[],"7":[],"8":[]},sameCat={"5":{},"6":{},"7":{},"8":{}},comp={};for(const x of r){const d=date(x[kd]);if(!d)continue;const m=d.getMonth()+1;if(m<5||m>8)continue;const n=String(x[kc]||"Chưa phân loại").trim(),v=num(x[kr]);if(!comp[n])comp[n]={name:n,"5":0,"6":0,"7":0,"8":0};comp[n][String(m)]+=v;if(d.getDate()<=11)sameCat[String(m)][n]=(sameCat[String(m)][n]||0)+v}for(const m of [5,6,7,8]){const total=Object.values(comp).reduce((s,x)=>s+(x[String(m)]||0),0);catMonth[String(m)]=Object.values(comp).map(x=>({name:x.name,dt:x[String(m)]||0,share:total?(x[String(m)]||0)/total*100:0})).sort((a,b)=>b.dt-a.dt)}return{catMonth,catComp:Object.values(comp),sameCat}}
function load(){try{return JSON.parse(fs.readFileSync(LOCK,"utf8"))}catch{return{locked:true,months_locked:[5,6,7],monthly:[],daily:[],sameOverall:{},catMonth:{"5":[],"6":[],"7":[],"8":[]},catComp:[],sameCat:{"5":{},"6":{},"7":{},"8":{}}}}
function save(x){fs.writeFileSync(LOCK,JSON.stringify(x))}
function updatePage(d){let h=fs.readFileSync(HEALTH,"utf8"),a=h.indexOf("const monthly="),b=h.indexOf("let selected=8;",a);if(a<0||b<0)throw Error("health.html sai mẫu");h=h.slice(0,a)+"const monthly="+JSON.stringify(d.monthly||[])+";const daily="+JSON.stringify(d.daily||[])+";const sameOverall="+JSON.stringify(d.sameOverall||{})+";const catMonth="+JSON.stringify(d.catMonth||{})+";const catComp="+JSON.stringify(d.catComp||[])+";const sameCat="+JSON.stringify(d.sameCat||{})+";const stores="+JSON.stringify(d.stores||[])+";"+h.slice(b);fs.writeFileSync(HEALTH,h)}
function ingest(){const old=load(),files=fs.readdirSync(INBOX).filter(f=>/\.(xlsx|xls|csv)$/i.test(f)).map(f=>({p:path.join(INBOX,f),t:fs.statSync(path.join(INBOX,f)).mtimeMs})).sort((a,b)=>b.t-a.t);if(!files.length)throw Error("Chưa có file dữ liệu sức khỏe");let rv=null,ct=null;for(const z of files.slice(0,20)){try{const x=kind(z.p);if(x.rev)rv=revenue(x.r,x.k);if(x.cat)ct=categories(x.r,x.k)}catch(e){console.error(e)}}if(!rv&&!ct)throw Error("File không đúng mẫu");const d={...old,locked:true,months_locked:[5,6,7]};if(rv){const t8=rv.monthly.find(x=>x.Tháng===8);d.monthly=(old.monthly||[]).filter(x=>x.Tháng!==8);if(t8)d.monthly.push(t8);d.monthly.sort((a,b)=>a.Tháng-b.Tháng);d.daily=rv.daily;d.sameOverall={...(old.sameOverall||{}),...(rv.sameOverall||{})}}if(ct){d.catMonth={...(old.catMonth||{}),"8":ct.catMonth["8"]||[]};const c=Object.fromEntries((old.catComp||[]).map(x=>[x.name,{...x}]));for(const x of ct.catComp){if(!c[x.name])c[x.name]={name:x.name,"5":0,"6":0,"7":0,"8":0};c[x.name]["8"]=x["8"]||0}d.catComp=Object.values(c);d.sameCat={...(old.sameCat||{}),"8":ct.sameCat["8"]||{}}}save(d);updatePage(d);return d}
function groupId(e){return e.source?.type==="group"||e.source?.type==="room"?e.source.groupId||e.source.roomId:null}
function getCfg(){try{return JSON.parse(fs.readFileSync(CFG,"utf8"))}catch{return{totalGroupId:null,lastReminderKey:null}}}
function saveCfg(c){fs.writeFileSync(CFG,JSON.stringify(c))}
async function pushGroup(groupId,text){if(!groupId||!TOKEN)return false;const r=await fetch("https://api.line.me/v2/bot/message/push",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+TOKEN},body:JSON.stringify({to:groupId,messages:[{type:"text",text}]})});if(!r.ok){console.error("LINE PUSH",await r.text());return false}return true}
function reminderText(h,m){const k=`${h}:${String(m).padStart(2,"0")}`;return ({"09:30":"⏰ NHẮC VIỆC\nBC FRESH CHỢ SÁNG","12:00":"⏰ NHẮC VIỆC\nBC VỆ SINH THU NGÂN","14:00":"⏰ NHẮC VIỆC\nBC TỦ ĐÔNG MÁT KEM","20:30":"⏰ NHẮC VIỆC\nBC CHÂM HÀNG FMCG","21:00":"⏰ NHẮC VIỆC\nBC TẮT ĐÈN","22:00":"⏰ NHẮC VIỆC\nTRAO SAO, TỔNG KẾT"})[k]||null}
async function checkReminders(){const c=getCfg();if(!c.totalGroupId)return;const now=new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Ho_Chi_Minh"}));const msg=reminderText(now.getHours(),now.getMinutes());if(!msg)return;const key=`${now.getFullYear()}-${now.getMonth()+1}-${now.getDate()} ${now.getHours()}:${now.getMinutes()}`;if(c.lastReminderKey===key)return;if(await pushGroup(c.totalGroupId,msg)){c.lastReminderKey=key;saveCfg(c)}}
setInterval(()=>{checkReminders().catch(console.error)},20000);checkReminders().catch(console.error);
async function makeHtmlImage(){const id=Date.now().toString();const file=path.join(DATA,"bc_suc_khoe_"+id+".jpg");const browser=await puppeteer.launch({headless:true,args:["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage"]});try{const page=await browser.newPage();await page.setViewport({width:1200,height:900,deviceScaleFactor:1});await page.goto("http://127.0.0.1:"+PORT+"/suc-khoe?image="+id,{waitUntil:"networkidle0",timeout:30000});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:file,fullPage:true,type:"jpeg",quality:88});return "https://ng-bot-c0im.onrender.com/report-image/"+id+".jpg"}finally{await browser.close()}}
async function reply(t,text,imageUrl){const messages=[{type:"text",text}];if(imageUrl)messages.push({type:"image",originalContentUrl:imageUrl,previewImageUrl:imageUrl});const r=await fetch("https://api.line.me/v2/bot/message/reply",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+TOKEN},body:JSON.stringify({replyToken:t,messages})});if(!r.ok)console.error(await r.text())}
async function content(id,p){const r=await fetch("https://api-data.line.me/v2/bot/message/"+id+"/content",{headers:{Authorization:"Bearer "+TOKEN}});if(!r.ok)throw Error("LINE "+r.status);fs.writeFileSync(p,Buffer.from(await r.arrayBuffer()))}
app.get("/",(q,s)=>s.send("LINE Bot is running!"));app.get("/suc-khoe",(q,s)=>s.set("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate").type("html").send(fs.readFileSync(HEALTH,"utf8")));app.get("/report-image/:id.jpg",(q,s)=>{const f=path.join(DATA,"bc_suc_khoe_"+q.params.id+".jpg");if(!/^\d+$/.test(q.params.id)||!fs.existsSync(f))return s.sendStatus(404);s.set("Cache-Control","no-store, no-cache, must-revalidate");s.type("jpg").sendFile(f)});
app.post("/webhook",express.raw({type:"application/json"}),async(req,res)=>{const body=req.body.toString(),sig=req.headers["x-line-signature"],exp=crypto.createHmac("sha256",SECRET||"").update(body).digest("base64");if(!SECRET||sig!==exp)return res.sendStatus(401);res.sendStatus(200);for(const e of JSON.parse(body).events||[]){try{if(e.message?.type==="file"){const n=path.basename(e.message.fileName||"data.xlsx").replace(/[^\w.\- ]/g,"_");await content(e.message.id,path.join(INBOX,Date.now()+"_"+n));await reply(e.replyToken,"📥 Đã nhận file. Nhắn NẠP DỮ LIỆU SỨC KHỎE để cập nhật.");continue}if(e.message?.type!=="text")continue;const t=e.message.text.toLowerCase().replace(/\s+/g," ").trim();const gid=groupId(e);if(t==="đăng ký nhóm tổng"||t==="dang ky nhom tong"){if(!gid)throw Error("Lệnh này phải gửi trong nhóm LINE");const c=getCfg();c.totalGroupId=gid;c.lastReminderKey=null;saveCfg(c);await reply(e.replyToken,"✅ Đã đăng ký nhóm TỔNG.\n📢 Tất cả nhắc việc sẽ chỉ gửi vào nhóm này.");continue}if(t==="test nhắc"||t==="test nhac"){if(!gid)throw Error("TEST NHẮC chỉ dùng trong nhóm LINE");const c=getCfg();if(!c.totalGroupId){c.totalGroupId=gid;saveCfg(c);await reply(e.replyToken,"🧪 TEST NHẮC\n✅ Đã tự đăng ký nhóm hiện tại là NHÓM TỔNG.\n📢 Từ nay lịch nhắc chỉ gửi vào nhóm này.");}else if(c.totalGroupId!==gid){await reply(e.replyToken,"⚠️ Nhóm này không phải NHÓM TỔNG nên bot không test nhắc tại đây.");}else{await pushGroup(gid,"🧪 TEST NHẮC\n✅ Bot nhắc việc đang hoạt động.\n📢 Nhóm này là NHÓM TỔNG.");}continue}if(t==="bc sức khỏe"||t==="bc suc khoe"){const img=await makeHtmlImage();await reply(e.replyToken,"📊 BC SỨC KHỎE\nhttps://ng-bot-c0im.onrender.com/suc-khoe",img)}else if(t==="nạp dữ liệu sức khỏe"||t==="nap du lieu suc khoe"){ingest();await reply(e.replyToken,"✅ Đã cập nhật T8. T5–T7 vẫn khóa cứng.\n📊 https://ng-bot-c0im.onrender.com/suc-khoe")}else if(t==="nạp dữ liệu dt hôm nay"||t==="nap du lieu dt hom nay"){const fsx=fs.readdirSync(INBOX).filter(f=>/\.(xlsx|xls|csv)$/i.test(f)).sort((a,b)=>fs.statSync(path.join(INBOX,b)).mtimeMs-fs.statSync(path.join(INBOX,a)).mtimeMs)[0];if(!fsx)throw Error("Chưa có file DT HÔM NAY");const x=kind(path.join(INBOX,fsx));if(!x.rev)throw Error("File không phải DOANH THU");const z=revenue(x.r,x.k).monthly.find(a=>a.Tháng===8)||{offline:0,online:0,bills:0};fs.writeFileSync(DT,JSON.stringify({doanh_thu_offline:z.offline,doanh_thu_online:z.online,tong_bill:z.bills}));await reply(e.replyToken,"✅ Đã nạp dữ liệu DT HÔM NAY.")}}catch(err){console.error(err);if(e.replyToken)await reply(e.replyToken,"⚠️ "+err.message)}}});
app.listen(PORT,()=>console.log("LINE Bot running "+PORT));