const express=require('express');const fs=require('fs');const path=require('path');const XLSX=require('xlsx');
const DATA=path.join(__dirname,'data'),INBOX=path.join(DATA,'health_uploads');fs.mkdirSync(INBOX,{recursive:true});
const TOKEN=process.env.LINE_CHANNEL_ACCESS_TOKEN;
const AUTO=path.join(DATA,'auto_groups.json');
function load(){try{return JSON.parse(fs.readFileSync(AUTO,'utf8'))}catch{return{healthGroup:null,revenueGroup:null}}}
function save(x){fs.writeFileSync(AUTO,JSON.stringify(x))}
function gid(e){return e.source?.type==='group'?e.source.groupId:e.source?.type==='room'?e.source.roomId:null}
function cols(rows){return rows.length?Object.keys(rows[0]).map(x=>String(x).trim().toLowerCase()):[]}
function classify(file){try{const wb=XLSX.readFile(file,{cellDates:true});let cat=false,rev=false,fresh=false;for(const sn of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:null,raw:true});const k=cols(rows);if(k.includes('ngày xuất')&&(k.includes('ngành hàng bhx')||k.includes('ngành hàng'))&&k.includes('doanh thu'))cat=true;if(k.includes('ngày')&&(k.includes('doanh thu offline')||k.includes('doanh thu online')))rev=true;if((k.includes('tên sản phẩm')||k.includes('tên sp')||k.includes('sản phẩm'))&&(k.includes('tổng sl bán')||k.includes('sl bán'))&&(k.includes('sl mất mát kiểm kê')||k.includes('sl mất mát')||k.includes('sl hủy tồn')||k.includes('sl hủy')))fresh=true}return{cat,rev,fresh}}catch{return{cat:false,rev:false,fresh:false}}}
async function reply(token,text){if(!TOKEN||!token)return;await fetch('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+TOKEN},body:JSON.stringify({replyToken:token,messages:[{type:'text',text}]})})}
async function download(id,dest){const r=await fetch('https://api-data.line.me/v2/bot/message/'+id+'/content',{headers:{Authorization:'Bearer '+TOKEN}});if(!r.ok)throw Error('LINE content '+r.status);fs.writeFileSync(dest,Buffer.from(await r.arrayBuffer()))}
const originalPost=express.application.post;express.application.post=function(route,...handlers){if(route!=='/webhook')return originalPost.call(this,route,...handlers);const last=handlers.length-1,original=handlers[last];handlers[last]=async function(req,res,next){try{const raw=Buffer.isBuffer(req.body)?req.body.toString():String(req.body||'');const body=JSON.parse(raw);const a=load();for(const e of body.events||[]){const id=gid(e),t=String(e.message?.text||'').trim().toLowerCase().replace(/\s+/g,' ');if(id&&e.message?.type==='text'){if(['đăng ký nhóm sức khỏe','dang ky nhom suc khoe','đăng ký nhóm sức khoẻ','dang ky nhom suc khoe'].includes(t)){a.healthGroup=id;save(a);await reply(e.replyToken,'✅ ĐÃ ĐĂNG KÝ NHÓM SỨC KHỎE');continue}if(['đăng ký nhóm dt','dang ky nhom dt','đăng ký nhóm doanh thu','dang ky nhom doanh thu'].includes(t)){a.revenueGroup=id;save(a);await reply(e.replyToken,'✅ ĐÃ ĐĂNG KÝ NHÓM DT');continue}}if(id&&e.message?.type==='file'){const n=path.basename(e.message.fileName||'data.xlsx').replace(/[^\w.\- ]/g,'_');const dest=path.join(INBOX,Date.now()+'_'+n);await download(e.message.id,dest);const k=classify(dest);const g=load();if(g.healthGroup===id){const hp=path.join(DATA,'health_pending.json');let q=[];try{q=JSON.parse(fs.readFileSync(hp,'utf8'))}catch{};q.push({path:dest,groupId:id,type:k.cat?'T8_NGANH_HANG':k.rev?'T8_DOANH_THU':k.fresh?'FRESH':'UNKNOWN'});fs.writeFileSync(hp,JSON.stringify(q));await reply(e.replyToken,`📥 ĐÃ NHẬN FILE ${k.cat?'T8 NGÀNH HÀNG':k.rev?'T8 DOANH THU':k.fresh?'FRESH':'KHÔNG XÁC ĐỊNH'}\n📦 ${q.length}/3 FILE SỨC KHỎE`);continue}if(g.revenueGroup===id&&k.rev){const rp=path.join(DATA,'revenue_pending.json');let q=[];try{q=JSON.parse(fs.readFileSync(rp,'utf8'))}catch{};q.push({path:dest,groupId:id});fs.writeFileSync(rp,JSON.stringify(q));await reply(e.replyToken,'📥 ĐÃ NHẬN FILE DOANH THU');continue}}}req.body=Buffer.from(JSON.stringify(body))}catch(err){console.error('PATCH',err)}return original.apply(this,arguments)};return originalPost.call(this,route,...handlers)};
console.log('STARTUP PATCH: GROUP REGISTRATION + 3 FILE ROUTER');