const express=require('express');const fs=require('fs');const path=require('path');
const DATA=path.join(__dirname,'data');fs.mkdirSync(DATA,{recursive:true});
const CFG=path.join(DATA,'line_groups.json');
function load(){try{return JSON.parse(fs.readFileSync(CFG,'utf8'))}catch{return{totalGroupId:null,lastReminderKey:null}}}
function save(x){fs.writeFileSync(CFG,JSON.stringify(x))}
function gid(e){return e.source?.type==='group'?e.source.groupId:e.source?.type==='room'?e.source.roomId:null}
function isRegistration(t){return ['đăng ký nhóm','dang ky nhom','đăng ký nhóm tổng','dang ky nhom tong','đăng ký nhóm sức khỏe','dang ky nhom suc khoe','đăng ký nhóm sức khoẻ','đăng ký nhóm dt','dang ky nhom dt','đăng ký nhóm doanh thu','dang ky nhom doanh thu'].includes(t)}
const originalPost=express.application.post;express.application.post=function(route,...handlers){if(route!=='/webhook')return originalPost.call(this,route,...handlers);const last=handlers.length-1,original=handlers[last];handlers[last]=async function(req,res,next){try{const raw=Buffer.isBuffer(req.body)?req.body.toString():String(req.body||'');const body=JSON.parse(raw);const c=load();const kept=[];for(const e of body.events||[]){const id=gid(e);const t=String(e.message?.text||'').trim().toLowerCase().replace(/\s+/g,' ');if(e.message?.type==='file'&&id){c.totalGroupId=id;save(c)}if(e.message?.type==='text'&&isRegistration(t)){if(e.replyToken&&process.env.LINE_CHANNEL_ACCESS_TOKEN){await fetch('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.LINE_CHANNEL_ACCESS_TOKEN},body:JSON.stringify({replyToken:e.replyToken,messages:[{type:'text',text:'ℹ️ Bot đã bỏ chức năng ĐĂNG KÝ NHÓM.\n📥 Hãy gửi file vào NHÓM DATA, sau đó dùng lệnh báo cáo cũ.'}]})})}continue}kept.push(e)}body.events=kept;req.body=Buffer.from(JSON.stringify(body))}catch(err){console.error('DATA_ONLY_PATCH',err)}return original.apply(this,arguments)};return originalPost.call(this,route,...handlers)};
console.log('DATA-ONLY MODE: NO GROUP REGISTRATION; FILE GROUP AUTO-REMINDER TARGET');
