const express=require('express');const fs=require('fs');const path=require('path');
const DATA=path.join(__dirname,'data');fs.mkdirSync(DATA,{recursive:true});const TARGET=path.join(DATA,'nhom_tong.json');
const TOKEN=process.env.LINE_CHANNEL_ACCESS_TOKEN;
function loadTarget(){try{return JSON.parse(fs.readFileSync(TARGET,'utf8')).to||null}catch{return null}}
let target=loadTarget();
function saveTarget(t){target=t;fs.writeFileSync(TARGET,JSON.stringify({to:t,updated_at:new Date().toISOString()}))}
async function lineReply(replyToken,text){if(!TOKEN||!replyToken)return;const r=await fetch('https://api.line.me/v2/bot/message/reply',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+TOKEN},body:JSON.stringify({replyToken,messages:[{type:'text',text}]})});if(!r.ok)console.error('TEST_NHAC_REPLY',await r.text())}
async function push(text){if(!TOKEN||!target)return false;const r=await fetch('https://api.line.me/v2/bot/message/push',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+TOKEN},body:JSON.stringify({to:target,messages:[{type:'text',text}]})});if(!r.ok){console.error('PUSH_NHAC',await r.text());return false}return true}
const originalPost=express.application.post;
express.application.post=function(route,...handlers){if(route!=='/webhook')return originalPost.call(this,route,...handlers);const last=handlers.length-1,original=handlers[last];handlers[last]=async function(req,res,next){try{const body=Buffer.isBuffer(req.body)?req.body.toString():String(req.body||'');if(body){for(const e of (JSON.parse(body).events||[])){const text=String(e.message?.text||'').trim().toLowerCase().replace(/\s+/g,' ');if(text==='test nhắc'||text==='test nhac'){const id=e.source?.groupId||e.source?.roomId;if(id)saveTarget(id);await lineReply(e.replyToken,id?'✅ TEST NHẮC OK — đã ghi nhận NHÓM TỔNG.':'⚠️ TEST NHẮC nhận được nhưng chưa xác định được nhóm.')}}}}catch(err){console.error('PATCH_WEBHOOK',err)}return original.apply(this,arguments)};return originalPost.call(this,route,...handlers)};
const SCHEDULE=[['09:30','📢 NHẮC VIỆC\nBC FRESH CHỢ SÁNG'],['12:00','📢 NHẮC VIỆC\nBC VỆ SINH THU NGÂN'],['14:00','📢 NHẮC VIỆC\nBC TỦ ĐÔNG MÁT KEM'],['20:30','📢 NHẮC VIỆC\nBC CHÂM HÀNG FMCG'],['21:00','📢 NHẮC VIỆC\nBC TẮT ĐÈN'],['22:00','📢 NHẮC VIỆC\nTRAO SAO, TỔNG KẾT']];
let last='';
function tick(){try{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const g=k=>p.find(x=>x.type===k)?.value||'';const date=g('year')+'-'+g('month')+'-'+g('day'),hm=g('hour')+':'+g('minute');const job=SCHEDULE.find(x=>x[0]===hm);if(job){const key=date+' '+hm;if(key!==last){last=key;push(job[1])}}}catch(e){console.error('SCHEDULER',e)}}
setInterval(tick,10000);tick();
console.log('REMINDER PATCH v3 LOADED',target?'TARGET_READY':'TARGET_WAITING');